## Structured and Record Arrays

You may have noticed up until now that ndarray is a homogeneous data container; that is, it represents a block of memory in which each element takes up the same number of bytes, determined by the dtype. On the surface, this would appear to not allow you to represent heterogeneous or tabular-like data. A structured array is an ndarray in which each element can be thought of as representing a struct in C (hence the “struc- tured” name) or a row in a SQL table with multiple named fields:

In [2]:
import numpy as np

In [4]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)

In [5]:
# sarr is an array of tuples (strictly speaking: tuples-like objects)
print(sarr)

[(1.5, 6) (3.141592653589793, -2)]


In [6]:
# we still can use index to get a tuple
sarr[0]

(1.5, 6)

In [7]:
sarr[1]

(3.141592653589793, -2)

In [10]:
# standard indexing doesn't work anymore
sarr[0,0]

IndexError: too many indices for array

In [16]:
# but this one works
sarr[0][0]

1.5

In [12]:
# we can also use name of columns from dtype
sarr[0]['x']

1.5

In [19]:
# or in different order
sarr['x'][0]

1.5

In [13]:
sarr[0]['y']

6

In [14]:
sarr[1]['x']

3.1415926535897931

In [15]:
sarr[1]['y']

-2

In [17]:
# we may also access columns using their names
sarr['x']

array([ 1.5       ,  3.14159265])

In [18]:
sarr['y']

array([ 6, -2], dtype=int32)

In [20]:
# we may also do slicing
sarr['x'][1:]

array([ 3.14159265])